name: publish to NPM

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '14.x'
        registry-url: https://registry.npmjs.org/

    - name: Running npm install
      run: npm install

    - name: Running npm test
      run: npm run test

    - name: Running npm build
      run: npm run build

    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
